export const tasks = [
  {
    id: 1,
    title: "Complete Project Report",
    dueDate: "2024-08-24",
    priority: "High",
  },
  {
    id: 2,
    title: "Meeting with Design Team",
    dueDate: "2024-08-25",
    priority: "Medium",
  },
  {
    id: 3,
    title: "Update Website Content",
    dueDate: "2024-08-26",
    priority: "Low",
  },
  { id: 4, title: "Client Follow-Up", dueDate: "2024-08-27", priority: "High" },
  {
    id: 5,
    title: "Prepare Presentation Slides",
    dueDate: "2024-08-28",
    priority: "Medium",
  },
  {
    id: 6,
    title: "Review Financial Reports",
    dueDate: "2024-08-29",
    priority: "Low",
  },
  {
    id: 7,
    title: "Plan Marketing Strategy",
    dueDate: "2024-08-30",
    priority: "High",
  },
  { id: 8, title: "Team Lunch", dueDate: "2024-08-31", priority: "Low" },
  {
    id: 9,
    title: "Fix Bugs in Application",
    dueDate: "2024-09-01",
    priority: "Medium",
  },
  {
    id: 10,
    title: "Organize Workspace",
    dueDate: "2024-09-02",
    priority: "Low",
  },
  {
    id: 11,
    title: "Write Blog Post",
    dueDate: "2024-09-03",
    priority: "Medium",
  },
  {
    id: 12,
    title: "Update User Documentation",
    dueDate: "2024-09-04",
    priority: "High",
  },
  {
    id: 13,
    title: "Conduct Code Review",
    dueDate: "2024-09-05",
    priority: "Medium",
  },
  {
    id: 14,
    title: "Schedule Team Meeting",
    dueDate: "2024-09-06",
    priority: "Low",
  },
  {
    id: 15,
    title: "Research New Tools",
    dueDate: "2024-09-07",
    priority: "Medium",
  },
  {
    id: 16,
    title: "Design New Feature",
    dueDate: "2024-09-08",
    priority: "High",
  },
  {
    id: 17,
    title: "Optimize Application Performance",
    dueDate: "2024-09-09",
    priority: "High",
  },
  {
    id: 18,
    title: "Prepare Quarterly Report",
    dueDate: "2024-09-10",
    priority: "Medium",
  },
  {
    id: 19,
    title: "Update Project Plan",
    dueDate: "2024-09-11",
    priority: "Low",
  },
  {
    id: 20,
    title: "Review New Policies",
    dueDate: "2024-09-12",
    priority: "Medium",
  },
];
